version: "3"

services:
  redis:
    container_name: native-redis
    image: redis
  nginx:
    container_name: native-nginx
    restart: always
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - api
      - client
  api:
    container_name: native-server
    build: ./server
    volumes:
      - ./server:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=mongodb+srv://admin:admin@like-a-native.oqdhp.mongodb.net/native?retryWrites=true&w=majority
      - SERVER_PORT=5000
      - IMAGE_UPLOAD_PATH=./public/images
      - MAX_FILE_UPLOAD=1000000
      - JWT_EXPIRE=30d
      - JWT_SECRET=eklwnfererwer
      - JWT_COOKIE_EXPIRE=30
      - REDIS_HOST=redis
      - REDIS_PORT=6379s
      - GOOGLE_CLIENT_ID=766859198689-0jjn5g33vto6gbbvlnbhsqat62c4s88g.apps.googleusercontent.com
      - GOOGLE_BUCKET_ID=like-a-native-words
      - GOOGLE_PROJECT_ID=like-a-native-speaker
    command: /app/entrypoint.sh
  db:
    container_name: native-db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data
  client:
    container_name: native-client
    build: ./client
    volumes:
    - ./client:/app
    command: /app/entrypoint.sh