version: "3"

services:
  nginx:
    container_name: native-nginx
    restart: always
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - api
      - client
  api:
    container_name: native-server
    build: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=db:27017
      - SERVER_PORT=5000
  db:
    container_name: native-db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data
  client:
    container_name: native-client
    build: ./client
    volumes:
    - /app/node_modules
    - ./client:/app